name: ci



on: [push, pull_request, workflow_dispatch]



jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout the code"
        id: checkout
        uses: actions/checkout@v3.3.0



      ## ---------- TEST
      - name: "Setup golang"
        id: setup-golang
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19

      - name: "Run Unit Tests"
        id: unit-tests
        run: cd src && go test



      ## ---------- BUILD
      - name: "Login to Container Registry"
        id: registry-login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: "Setup QEMU"
        id: setup-qemu
        uses: docker/setup-qemu-action@v2.1.0

      - name: "Setup Buildx"
        id: setup-buildx
        uses: docker/setup-buildx-action@v2.3.0

      - name: "Setup Build Context"
        id: setup-context
        run: |
          [ -d .build ] && rm -rf .build
          mkdir .build && cp src/{math.go,go.mod} docker/Dockerfile .build

      - name: "Build container image"
        id: build-image
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          file: .build/Dockerfile
          context: .build
          tags: |
            aleroxac/fullcycle:desafio-ci
